### ISSUE TITLE
how to use

### ISSUE THREAD

**Issue by fastcode3d** [A-Dying-Pig/OpenGL_NeuralTexture#2]
Hello, I want to render data with this project. Can you give me some suggestions on how to use this project?

**Comment by fastcode3d** [comment]
I compiled the file and ran it without error. But the black screen is displayed. Is there anything wrong?

**Comment by A-Dying-Pig** [comment]
In the main.cpp, line 37, set **enable_output** = false. The rendered scene will be displayed on the screen. Otherwise the frame and some other information will be written into files. (see line 41 42 43, if you want to output, you may set directories correctly)

When the scene is displayed on the screen correctly, you should see a vase or basketball.

**Comment by fastcode3d** [comment]
Thank you very much for your work. I can run it now.
