### ISSUE TITLE
Render Vase

### ISSUE THREAD

**Issue by TaplierShiru** [A-Dying-Pig/OpenGL_NeuralTexture#3]
Hello, thank you for this repository.
I'm trying to render data for the vase, but in frame folder I get something like that,

![photo_2020-01-27_12-23-35](https://user-images.githubusercontent.com/45129308/73242287-07e10300-41be-11ea-89ff-8ecbfff187c3.jpg)

Also I render data for the basketball ball and it work fine 
![0000](https://user-images.githubusercontent.com/45129308/73242981-d9fcbe00-41bf-11ea-8504-32f1ea6e3d37.png)

For rendering the vase in the main.cpp file in the lines 283 and 298 I change path to obj and jpg files with the vase.
But it doesn't seem to work. Could you please point out how exactly I should change the code to render the vase?

**Comment by A-Dying-Pig** [comment]
Thanks for you practice and question. Please pull the latest repository. In the main.cpp line 40, set object_id = 1 to load vase. (please also see README)

**Comment by A-Dying-Pig** [comment]
The reason why the replacement of texture and object file doesn't work is that basketball and vase scale and translate in different ways (assuming the motion of the camera stays the same). So what you get is the view "in the vase' instead of "around the vase". Therefore you see something black as you shown in the picture.  You can refer to the latest code to check how the models are different in the way to scale and translate. (The reason to scale and translate model is that models are naturally made in different sizes and for better demonstration)

**Comment by TaplierShiru** [comment]
Thank you for your answer. I did data rendering for both the ball and the vase and all works fine.
Again, thank you!
